This is the final structure upgrade for us. In this part we will gather together all of our functions to class. This class we'll be our layer class.

In [1]:
import cv2 as cv
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [4]:
def prepare_the_image(imgPath):
    img = cv.imread(imgPath, cv.IMREAD_GRAYSCALE)
    img = img/255
    flatten = img.flatten()
    return flatten

In [5]:
flattenV = prepare_the_image("../Data/Train/Vertical.png")
flattenH = prepare_the_image("../Data/Train/Horizontal.png")

In [6]:
dataset = np.array([flattenV, flattenH])
labels = np.array([[0, 1]]).T

Let's start creating your layer class. This class will be have a constructor method that will create a random weights. We will only give size of the matrix. Rest is  same

In [7]:
class Layer:
    def __init__(self, input_size, output_size):
        self.weights = np.random.rand(input_size, output_size)
        print("Starting weights are . . .")
        print(self.weights)

    def feed_forward(self, input):
        weighted_sum = np.dot(input, self.weights)
        output = sigmoid(weighted_sum)
        return output

    def back_propagation(self, input, output, labels):
        error = output - labels
        adjustment = error * sigmoid_der(output)
        weights_update = np.dot(input.T, adjustment)
        self.weights -= weights_update

In [8]:
layer1 = Layer(9, 1)

Starting weights are . . .
[[0.09508795]
 [0.71008363]
 [0.05492891]
 [0.09920901]
 [0.67865868]
 [0.50071822]
 [0.23306695]
 [0.35551141]
 [0.11542517]]


In [9]:
for i in range(100):
    output = layer1.feed_forward(dataset)
    layer1.back_propagation(dataset, output, labels)

In [10]:
print("Input dataset :: \n", dataset)

Input dataset :: 
 [[0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]]


In [11]:
print("Labels are :: \n", labels)

Labels are :: 
 [[0]
 [1]]


In [12]:
print("Final weights are . . . \n", layer1.weights)

Final weights are . . . 
 [[ 0.09508795]
 [-1.68789331]
 [ 0.05492891]
 [ 1.68568376]
 [-0.1328435 ]
 [ 2.08719298]
 [ 0.23306695]
 [-2.04246553]
 [ 0.11542517]]
